name = "modem"
version = "2.1.2"

description = "A friendly Lustre package to help you handle routing, links, and manage URLs."
repository = { type = "github", user = "hayleigh-dot-dev", repo = "modem" }
licences = ["MIT"]

links = [
    { title = "Lustre", href = "https://hexdocs.pm/lustre/" },
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
lustre = ">= 5.1.0 and < 6.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
birdie = ">= 1.3.0 and < 2.0.0"
